### PR TITLE
added new sound

### PR DESCRIPTION
**Pull request by anvaymishra1**
Screenshot_20191001-105354

### CODE REVIEW

**Comment by ashutoshsingh05** [comment]
Are you sure you wish to change all these files ? @anvaymishra1

**Comment by anvaymishra1** [comment]
changes done . Please review

**Review by thecodepapaya — CHANGES_REQUESTED** [review]
Remove pubspec.lock and flutter_export_environment.sh from the commit. They are not needed.
Also, change the screenshot in README.md to reflect the changes in app screenshot.

**Review by thecodepapaya — CHANGES_REQUESTED** [review]
The better way to update the screen shot would be to replace the flutter_01.png with updated screenshot

**Review by thecodepapaya — APPROVED** [review]

**Pull request merged**
